module.exports = Object.freeze({
  DELIVERY_FEE: 1500,
  RIDER_COMMISSION_PERCENT: 40,
  RIDER_COMMISSION_AMOUNT: 600,
  SERVICEPAY_PERCENT: 60,
  SERVICEPAY_AMOUNT: 900,
  WITHDRAWAL_MODE: "MANUAL",
});
