const express = require("express");
const controller = require("../controllers/edupay.controller");
const { protect, adminOnly } = require("../middleware/auth.middleware");
const { loadStaffRole, requirePermission } = require("../middleware/staffPermission.middleware");
const router = express.Router();
const view = [protect, adminOnly("HEAD_OFFICE"), loadStaffRole, requirePermission("edupay.view")];
const manage = [protect, adminOnly("HEAD_OFFICE"), loadStaffRole, requirePermission("edupay.manage")];
router.get("/readiness", ...view, controller.adminReadiness);
router.get("/overview", ...view, controller.adminOverview);
router.get("/settings", ...view, controller.adminSettings);
router.patch("/settings", ...manage, controller.adminSettings);
router.get("/schools", ...view, controller.adminSchools);
router.patch("/schools/:schoolId", ...manage, controller.adminSchoolAction);
router.post("/schools/:schoolId/users", ...manage, controller.adminCreateSchoolUser);
router.get("/fees", ...view, controller.adminFees);
router.get("/fees/:feeId", ...view, controller.adminFees);
router.patch("/fees/:feeId", ...manage, controller.adminFeeAction);
router.get("/parents", ...view, controller.adminPlans);
router.get("/children", ...view, controller.adminPlans);
router.get("/plans", ...view, controller.adminPlans);
router.get("/repayments", ...view, controller.adminRepayments);
router.get("/settlements", ...view, controller.adminSettlements);
router.post("/plans/:planId/settlements", ...manage, controller.adminCreateSettlement);
router.post("/settlements/:settlementId/process", ...manage, controller.adminSettlementProcess);
router.post("/settlements/:settlementId/requery", ...manage, controller.adminSettlementRequery);
router.patch("/settlements/:settlementId", ...manage, controller.adminSettlementActionSecure);
router.put("/schools/:schoolId/settlement-account", ...manage, controller.adminSettlementAccount);
router.post("/schools/:schoolId/settlement-account/verify", ...manage, controller.adminVerifySettlementAccount);
router.get("/sponsors", ...view, controller.adminSponsors);
router.get("/transactions", ...view, controller.adminTransactions);
router.get("/reconciliation", ...view, controller.adminTransactions);
router.get("/audit", ...view, controller.adminAudit);
router.get("/audit-logs", ...view, controller.adminAudit);
module.exports = router;