const express = require("express");
const controller = require("../controllers/edupay.controller");
const { headOffice } = require("../middleware/edupay.middleware");
const router = express.Router();
router.use(...headOffice);
router.get("/overview", controller.adminOverview);
router.get("/settings", controller.adminSettings);
router.patch("/settings", controller.adminSettings);
router.get("/schools", controller.adminSchools);
router.patch("/schools/:schoolId", controller.adminSchoolAction);
router.post("/schools/:schoolId/users", controller.adminCreateSchoolUser);
router.get("/fees", controller.adminFees);
router.get("/fees/:feeId", controller.adminFees);
router.patch("/fees/:feeId", controller.adminFeeAction);
router.get("/parents", controller.adminPlans);
router.get("/children", controller.adminPlans);
router.get("/plans", controller.adminPlans);
router.get("/repayments", controller.adminRepayments);
router.get("/settlements", controller.adminSettlements);
router.post("/plans/:planId/settlements", controller.adminCreateSettlement);
router.patch("/settlements/:settlementId", controller.adminSettlementAction);
router.get("/sponsors", controller.adminSponsors);
router.get("/transactions", controller.adminTransactions);
router.get("/reconciliation", controller.adminTransactions);
router.get("/audit", controller.adminAudit);
router.get("/audit-logs", controller.adminAudit);
module.exports = router;