const router = require("express").Router();
const c = require("../controllers/interstateLogistics.controller");
const { protect, adminOnly } = require("../middleware/auth.middleware");
router.use(protect, adminOnly("HEAD_OFFICE"));
router.get("/shipments", c.adminShipments);
router.get("/overview", c.adminOverview);
router.get("/exceptions", c.adminExceptions);
router.get("/returns", c.adminReturns);
router.get("/routes", c.adminRoutes);
router.post("/routes", c.createRoute);
router.patch("/routes/:id", c.updateRoute);
router.get("/trips", c.listTrips);
router.post("/trips", c.createTrip);
router.patch("/trips/:id/status", c.updateTripStatus);
router.post("/drivers", c.createDriver);
router.post("/vehicles", c.createVehicle);
router.get("/drivers", c.listDrivers);
router.get("/vehicles", c.listVehicles);
module.exports = router;