const router = require("express").Router();
const c = require("../controllers/interstateLogistics.controller");
const { protect, adminOnly } = require("../middleware/auth.middleware");
const { loadStaffRole, requirePermission } = require("../middleware/staffPermission.middleware");
const office = require("../controllers/interstateOffice.controller");
router.use(protect, adminOnly("HEAD_OFFICE"), loadStaffRole);
router.get("/shipments", c.adminShipments);
router.get("/customers", requirePermission("branch.delivery.manage"), office.customers);
router.post("/office-quote", requirePermission("branch.delivery.manage"), office.officeQuote);
router.post("/shipments", requirePermission("branch.delivery.manage"), office.create);
router.get("/shipments/:id", requirePermission("branch.delivery.view"), office.detail);
router.get("/shipments/:id/receipt", requirePermission("branch.delivery.view"), office.receipt);
router.get("/shipments/:id/riders", requirePermission("branch.delivery.manage"), office.riders);
router.post("/shipments/:id/assign-rider", requirePermission("branch.delivery.manage"), office.assign);
router.patch("/shipments/:id/status", requirePermission("branch.delivery.manage"), office.status);
router.get("/overview", c.adminOverview);
router.get("/exceptions", c.adminExceptions);
router.get("/returns", c.adminReturns);
router.get("/routes", c.adminRoutes);
router.get("/branches", c.adminBranches);
router.post("/routes", c.createRoute);
router.patch("/routes/:id", c.updateRoute);
router.patch("/routes/:id/activate", c.activateRoute);
router.patch("/routes/:id/deactivate", c.deactivateRoute);
router.post("/routes/:id/archive", c.archiveRoute);
router.post("/routes/:id/restore", c.restoreRoute);
router.get("/trips", c.listTrips);
router.post("/trips", c.createTrip);
router.patch("/trips/:id/status", c.updateTripStatus);
router.post("/drivers", c.createDriver);
router.patch("/drivers/:id", c.updateDriver);
router.delete("/drivers/:id", c.deleteDriver);
router.post("/vehicles", c.createVehicle);
router.patch("/vehicles/:id", c.updateVehicle);
router.delete("/vehicles/:id", c.deleteVehicle);
router.get("/drivers", c.listDrivers);
router.get("/vehicles", c.listVehicles);
module.exports = router;