const express = require("express");
const c = require("../controllers/branch.controller");
const { protect } = require("../middleware/auth.middleware");
const { loadStaffRole, requireAnyPermission, enforceActiveBranchScope, STAFF_PERMISSIONS: P } = require("../middleware/staffPermission.middleware");
const router = express.Router();
router.use(protect, loadStaffRole, enforceActiveBranchScope);
router.route("/").get(requireAnyPermission(P.BRANCHES_VIEW, P.BRANCH_DASHBOARD_VIEW), c.list).post(requireAnyPermission(P.BRANCHES_MANAGE), c.create);
router.get("/overview", requireAnyPermission(P.BRANCH_DASHBOARD_VIEW, P.BRANCHES_VIEW), c.overview);
router.get("/dashboard", requireAnyPermission(P.BRANCH_DASHBOARD_VIEW), c.dashboard);
router.get("/reports", requireAnyPermission(P.BRANCH_REPORTS_VIEW, P.BRANCHES_REPORTS_VIEW), c.reports);
router.route("/targets").get(requireAnyPermission(P.BRANCH_TARGETS_VIEW), c.targets).post(requireAnyPermission(P.BRANCHES_TARGETS_MANAGE), c.targets);
router.put("/targets/:targetId/progress", requireAnyPermission(P.BRANCHES_TARGETS_MANAGE, P.BRANCH_APPROVALS_SUBMIT), c.progress);
router.route("/approvals").get(requireAnyPermission(P.BRANCH_APPROVALS_VIEW, P.BRANCHES_APPROVALS_VIEW), c.approvals).post(requireAnyPermission(P.BRANCH_APPROVALS_SUBMIT), c.submitApproval);
router.put("/approvals/:requestId/review", requireAnyPermission(P.BRANCHES_APPROVALS_MANAGE), c.reviewApproval);
router.route("/operational-requests").get(requireAnyPermission(P.BRANCH_DASHBOARD_VIEW), c.operational).post(requireAnyPermission(P.BRANCH_APPROVALS_SUBMIT), c.operational);
router.get("/audit", requireAnyPermission(P.BRANCHES_APPROVALS_VIEW), c.audit);
router.get("/:branchId/members", requireAnyPermission(P.BRANCH_STAFF_VIEW, P.BRANCHES_VIEW), c.members);
router.post("/:branchId/members", requireAnyPermission(P.BRANCH_STAFF_MANAGE, P.BRANCHES_STAFF_MANAGE), c.members);
router.delete("/:branchId/members/:userId", requireAnyPermission(P.BRANCH_STAFF_MANAGE, P.BRANCHES_STAFF_MANAGE), c.removeMember);
router.post("/:branchId/customers", requireAnyPermission(P.BRANCH_CUSTOMERS_CREATE), c.createCustomer);
router.put("/:branchId/activate", requireAnyPermission(P.BRANCHES_MANAGE), c.activate);
router.put("/:branchId/manager", requireAnyPermission(P.BRANCHES_STAFF_MANAGE), c.assignManager);
router.route("/:branchId").get(requireAnyPermission(P.BRANCHES_VIEW, P.BRANCH_DASHBOARD_VIEW), c.get).put(requireAnyPermission(P.BRANCHES_MANAGE), c.update);
module.exports = router;