const router = require("express").Router();
const c = require("../controllers/interstateLogistics.controller");
const { protect } = require("../middleware/auth.middleware");
const { loadStaffRole, requirePermission } = require("../middleware/staffPermission.middleware");
const office = require("../controllers/interstateOffice.controller");
router.use(protect, loadStaffRole);
router.get("/shipments", requirePermission("branch.delivery.view"), c.listBranch);
router.get("/routes", requirePermission("branch.delivery.manage"), office.routes);
router.get("/customers", requirePermission("branch.delivery.manage"), office.customers);
router.post("/office-quote", requirePermission("branch.delivery.manage"), office.officeQuote);
router.post("/shipments", requirePermission("branch.delivery.manage"), office.create);
router.get("/shipments/:id", requirePermission("branch.delivery.view"), office.detail);
router.get("/shipments/:id/receipt", requirePermission("branch.delivery.view"), office.receipt);
router.get("/shipments/:id/riders", requirePermission("branch.delivery.manage"), office.riders);
router.patch("/shipments/:id/status", requirePermission("branch.delivery.manage"), office.status);
router.post("/shipments/:id/assign-rider", requirePermission("branch.delivery.manage"), office.assign);
router.patch("/shipments/:id/confirm-delivery-fallback", requirePermission("branch.delivery.manage"), c.confirmDeliveryFallback);
router.post("/shipments/:id/confirm-delivery-fallback", requirePermission("branch.delivery.manage"), c.confirmDeliveryFallback);
const action = (status) => (req, res, next) => { req.body.status = status; next(); };
router.patch("/shipments/:id/receive", requirePermission("branch.delivery.manage"), action("RECEIVED_AT_ORIGIN_HUB"), c.branchStatus);
router.patch("/shipments/:id/verify", requirePermission("branch.delivery.manage"), action("VERIFIED_AT_ORIGIN_HUB"), c.branchStatus);
router.patch("/shipments/:id/ready-for-dispatch", requirePermission("branch.delivery.manage"), action("READY_FOR_INTERSTATE_DISPATCH"), c.branchStatus);
module.exports = router;