const express = require("express");
const { protect, customerOnly, adminOnly } = require("../middleware/auth.middleware");
const c = require("../controllers/organizations.controller");
const router = express.Router();

// These endpoints intentionally do not expose member PII or unpublished records.
router.get("/public/search", c.publicSearch);
router.get("/public/:slug", c.publicView);
router.get("/public/cards/:cardNumber", c.verifyCard);

router.use(protect);
router.post("/", c.create);
router.get("/mine", c.mine);
router.get("/explore", c.explore);
router.get("/", c.mine);
router.post("/:organizationId/submit", c.submit);
router.patch("/:id/platform-status", adminOnly("SUPER_ADMIN", "ADMIN"), c.platformStatus);
router.post("/:organizationId/apply", customerOnly, c.apply);
router.get("/:organizationId/members", c.members);
router.get("/:organizationId/staff", c.staff);
router.post("/:organizationId/staff", c.addStaff);
router.delete("/:organizationId/staff/:staffId", c.removeStaff);
router.get("/:id", c.getCustomerOrganization);
router.get("/:id/dues", customerOnly, c.dues);
router.get("/:id/payments", customerOnly, c.payments);
router.get("/:id/card", customerOnly, c.myCard);
router.post("/:id/payments", customerOnly, c.pay);
router.post("/:id/annual-payment", customerOnly, c.pay);
// Authenticated organization dashboard surface (never the platform admin API).
router.get("/:organizationId/dashboard", c.dashboardCanonical);
router.get("/:organizationId/dashboard/overview", c.dashboardOverview);
router.get("/:organizationId/dashboard/trends", c.dashboardTrends);
router.get("/:organizationId/dashboard/recent", c.dashboardRecent);
router.get("/:organizationId/members/search", c.memberList);
router.get("/:organizationId/members/:memberId/detail", c.memberDetail);
router.patch("/:organizationId/members/:memberId/detail", c.memberDetailPatch);
router.patch("/:organizationId/members/:memberId/status", c.memberStatus);
router.post("/:organizationId/members/:memberId/message", c.messageMember);
router.get("/:organizationId/applications", c.applicationList);
router.get("/:organizationId/applications/:applicationId", c.applicationDetail);
router.post("/:organizationId/applications/:applicationId/approve", c.approveApplication);
router.post("/:organizationId/applications/:applicationId/reject", c.rejectApplication);
router.get("/:organizationId/payment-history", c.paymentHistory);
router.get("/:organizationId/fees", c.feeList);
router.patch("/:organizationId/fees/:feeId", c.feeUpdate);
router.get("/:organizationId/fee-assignments/summary", c.feeAssignments);
router.get("/:organizationId/wallet/details", c.walletDetails);
router.get("/:organizationId/branches", c.branchList);
router.patch("/:organizationId/branches/:branchId", c.branchUpdate);
router.get("/:organizationId/staff/list", c.staffList);
router.patch("/:organizationId/staff/:staffId", c.staffUpdate);
router.get("/:organizationId/announcements", c.announcementList);
router.get("/:organizationId/cards", c.cardList);
router.get("/:organizationId/cards/:cardId", c.cardDetail);
router.get("/:organizationId/reports", c.report);
router.get("/:organizationId/audit", c.auditList);
router.get("/:organizationId/settings", c.settingsGet);
router.patch("/:organizationId/settings", c.settingsPatch);
router.post("/:organizationId/members/:memberId/approve", c.approveMember);
router.post("/:organizationId/branches", c.createBranch);
router.post("/:organizationId/custom-fields", c.createField);
router.post("/:organizationId/fees", c.createFee);
router.post("/:organizationId/fee-assignments", c.assignFee);
router.post("/:organizationId/fee-assignments/:assignmentId/pay", customerOnly, c.pay);
router.get("/:organizationId/wallet", c.wallet);
router.get("/:organizationId/treasury", c.treasury);
router.get("/:organizationId/settlement-accounts", c.settlementAccounts);
router.post("/:organizationId/settlement-accounts", c.settlementAccounts);
router.post("/:organizationId/settlement-accounts/resolve", c.resolveSettlementAccount);
router.get("/:organizationId/withdrawals", c.withdrawalList);
router.post("/:organizationId/withdrawals", c.withdraw);
router.get("/:organizationId/withdrawals/:withdrawalId", c.withdrawalDetail);
router.post("/:organizationId/withdrawals/:withdrawalId/approve", c.approveWithdrawal);
router.post("/:organizationId/withdrawals/:withdrawalId/reject", c.rejectWithdrawal);
router.post("/:organizationId/withdrawals/:withdrawalId/requery", c.requeryWithdrawal);
router.post("/:organizationId/announcements", c.announcements);
router.post("/:organizationId/cards", c.card);
module.exports = router;