const express = require("express");
const { protect, customerOnly, adminOnly } = require("../middleware/auth.middleware");
const controller = require("../controllers/solar.controller");
const router = express.Router();
const admins = adminOnly("HEAD_OFFICE", "ADMIN", "SUPER_ADMIN");
router.get("/packages", protect, controller.listPackages);
router.get("/packages/:packageId", protect, controller.getPackage);
router.post("/applications", protect, customerOnly, controller.submitApplication);
router.get("/my-applications", protect, customerOnly, controller.myApplications);
router.get("/my-applications/:applicationId", protect, customerOnly, controller.getMyApplication);
router.post("/applications/:applicationId/pay-deposit", protect, customerOnly, controller.payDeposit);
router.post("/applications/:applicationId/payments", protect, customerOnly, controller.pay);
router.get("/my-finance", protect, customerOnly, controller.myFinance);
router.get("/finance/:financeId", protect, customerOnly, controller.getFinance);
router.get("/finance/:financeId/schedule", protect, customerOnly, controller.financeSchedule);
router.get("/finance/:financeId/payments", protect, customerOnly, controller.financePayments);
router.post("/finance/:financeId/pay", protect, customerOnly, controller.payFinance);
router.get("/admin/settings", protect, admins, controller.getSettings);
router.put("/admin/settings", protect, admins, controller.updateSettings);
router.post("/admin/packages", protect, admins, controller.createPackage);
router.patch("/admin/packages/:packageId", protect, admins, controller.updatePackage);
router.delete("/admin/packages/:packageId", protect, admins, controller.deletePackage);
router.get("/admin/applications", protect, admins, controller.adminApplications);
router.get("/admin/finance", protect, admins, controller.adminFinance);
router.get("/admin/finance/:financeId", protect, admins, controller.adminFinanceDetail);
router.get("/admin/repayments", protect, admins, controller.adminRepayments);
router.get("/admin/overdue", protect, admins, controller.adminOverdue);
router.patch("/admin/applications/:applicationId/status", protect, admins, controller.transitionApplication);
router.patch("/admin/applications/:applicationId/approve", protect, admins, controller.approveApplication);
router.post("/admin/applications/:applicationId/install", protect, admins, controller.installApplication);
router.patch("/admin/applications/:applicationId/recovery", protect, admins, controller.recovery);
router.post("/admin/finance/:financeId/recovery", protect, admins, controller.openRecoveryCase);
router.get("/admin/dashboard", protect, admins, controller.dashboard);
router.get("/admin/reports", protect, admins, controller.reports);
module.exports = router;