import 'package:flutter/foundation.dart';
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
// ignore: avoid_web_libraries_in_flutter
import 'dart:html' as html;

import 'package:gal/gal.dart';
import 'package:screenshot/screenshot.dart';
import 'package:share_plus/share_plus.dart';

class BusinessWalletTransactionReceiptScreen extends StatefulWidget {
  final Map<String, dynamic> transaction;
  final String businessName;
  final String businessWalletId;

  const BusinessWalletTransactionReceiptScreen({
    super.key,
    required this.transaction,
    required this.businessName,
    required this.businessWalletId,
  });

  @override
  State<BusinessWalletTransactionReceiptScreen> createState() =>
      _BusinessWalletTransactionReceiptScreenState();
}

class _BusinessWalletTransactionReceiptScreenState
    extends State<BusinessWalletTransactionReceiptScreen> {
  static const Color primaryGreen = Color(0xFF08783E);

  final ScreenshotController screenshotController = ScreenshotController();

  bool isProcessing = false;

  Map<String, dynamic> get transaction => widget.transaction;

  String get businessName => widget.businessName;

  String get businessWalletId => widget.businessWalletId;

  double toDouble(dynamic value) {
    return double.tryParse(
          value?.toString() ?? '',
        ) ??
        0;
  }

  String money(dynamic value) {
    return '₦${toDouble(value).toStringAsFixed(2)}';
  }

  String textValue(
    dynamic value, {
    String fallback = '-',
  }) {
    final valueText = value?.toString().trim() ?? '';

    return valueText.isEmpty ? fallback : valueText;
  }

  String formatDateTime(dynamic value) {
    final raw = value?.toString().trim() ?? '';

    if (raw.isEmpty) {
      return '-';
    }

    try {
      final dt = DateTime.parse(raw).toLocal();

      final day = dt.day.toString().padLeft(2, '0');

      final month = dt.month.toString().padLeft(2, '0');

      final year = dt.year.toString();

      final hour = dt.hour.toString().padLeft(2, '0');

      final minute = dt.minute.toString().padLeft(2, '0');

      return '$day/$month/$year  $hour:$minute';
    } catch (_) {
      return raw;
    }
  }

  Map<String, dynamic> get metadata {
    final value = transaction['metadata'];

    if (value is Map) {
      return Map<String, dynamic>.from(
        value,
      );
    }

    return <String, dynamic>{};
  }

  bool get isCredit {
    return textValue(
          transaction['direction'],
          fallback: '',
        ).toUpperCase() ==
        'CREDIT';
  }

  String get status {
    return textValue(
      transaction['status'],
      fallback: 'SUCCESSFUL',
    ).toUpperCase();
  }

  String get receiptText {
    final buffer = StringBuffer();

    buffer.writeln(
      'SERVICEPAY BUSINESS WALLET RECEIPT',
    );
    buffer.writeln('');

    buffer.writeln(
      'Business: ${businessName.isEmpty ? 'ServicePay Business' : businessName}',
    );

    buffer.writeln(
      'Business ID: ${businessWalletId.isEmpty ? '-' : businessWalletId}',
    );

    buffer.writeln(
      'Description: ${textValue(transaction['narration'], fallback: 'Business transaction')}',
    );

    buffer.writeln(
      'Amount: ${money(transaction['amount'])}',
    );

    buffer.writeln(
      'Type: ${textValue(transaction['type'])}',
    );

    buffer.writeln(
      'Direction: ${textValue(transaction['direction'])}',
    );

    buffer.writeln(
      'Status: $status',
    );

    buffer.writeln(
      'Reference: ${textValue(transaction['reference'])}',
    );

    buffer.writeln(
      'Date: ${formatDateTime(transaction['createdAt'])}',
    );

    final counterparty = textValue(
      metadata['counterpartyBusinessWalletId'],
      fallback: '',
    );

    if (counterparty.isNotEmpty) {
      buffer.writeln(
        'Counterparty Business ID: $counterparty',
      );
    }

    final bank = textValue(
      metadata['bankName'],
      fallback: '',
    );

    if (bank.isNotEmpty) {
      buffer.writeln(
        'Bank: $bank',
      );
    }

    final accountNumber = textValue(
      metadata['accountNumber'],
      fallback: '',
    );

    if (accountNumber.isNotEmpty) {
      buffer.writeln(
        'Account Number: $accountNumber',
      );
    }

    final accountName = textValue(
      metadata['accountName'],
      fallback: '',
    );

    if (accountName.isNotEmpty) {
      buffer.writeln(
        'Account Name: $accountName',
      );
    }

    buffer.writeln('');
    buffer.writeln(
      'Generated by ServicePay',
    );

    return buffer.toString();
  }

  Future<Uint8List?> captureReceipt() async {
    try {
      return await screenshotController.capture(
        delay: const Duration(milliseconds: 150),
        pixelRatio: 2.5,
      );
    } catch (_) {
      return null;
    }
  }

  Future<void> copyReceipt() async {
    await Clipboard.setData(
      ClipboardData(
        text: receiptText,
      ),
    );

    if (!mounted) {
      return;
    }

    ScaffoldMessenger.of(context).showSnackBar(
      const SnackBar(
        content: Text(
          'Receipt copied successfully.',
        ),
      ),
    );
  }

  Future<void> shareReceipt() async {
    if (isProcessing) {
      return;
    }

    setState(() {
      isProcessing = true;
    });

    try {
      final bytes = await captureReceipt();

      if (bytes == null) {
        throw Exception(
          'Unable to capture receipt.',
        );
      }

      final reference = textValue(
        transaction['reference'],
        fallback: 'receipt',
      ).replaceAll(
        RegExp(r'[^A-Za-z0-9_-]'),
        '_',
      );

      await SharePlus.instance.share(
        ShareParams(
          text: 'ServicePay Business Wallet Receipt',
          files: <XFile>[
            XFile.fromData(
              bytes,
              mimeType: 'image/png',
              name: 'servicepay_$reference.png',
            ),
          ],
        ),
      );
    } catch (error) {
      if (!mounted) {
        return;
      }

      ScaffoldMessenger.of(context).showSnackBar(
        SnackBar(
          content: Text(
            error.toString().replaceFirst(
                  'Exception: ',
                  '',
                ),
          ),
        ),
      );
    } finally {
      if (mounted) {
        setState(() {
          isProcessing = false;
        });
      }
    }
  }

  Future<void> downloadReceipt() async {
    if (isProcessing) {
      return;
    }

    setState(() {
      isProcessing = true;
    });

    try {
      final bytes = await captureReceipt();

      if (bytes == null) {
        throw Exception(
          'Unable to capture receipt.',
        );
      }

      final reference = textValue(
        transaction['reference'],
        fallback: 'receipt',
      ).replaceAll(
        RegExp(r'[^A-Za-z0-9_-]'),
        '_',
      );

      final fileName = 'servicepay_$reference.png';

      if (kIsWeb) {
        final blob = html.Blob(
          <dynamic>[bytes],
          'image/png',
        );

        final url = html.Url.createObjectUrlFromBlob(
          blob,
        );

        final anchor = html.AnchorElement(
          href: url,
        )
          ..setAttribute(
            'download',
            fileName,
          )
          ..style.display = 'none';

        html.document.body?.children.add(
          anchor,
        );

        anchor.click();
        anchor.remove();

        html.Url.revokeObjectUrl(url);
      } else {
        await Gal.putImageBytes(
          bytes,
          album: 'ServicePay',
        );
      }

      if (!mounted) {
        return;
      }

      ScaffoldMessenger.of(context).showSnackBar(
        SnackBar(
          content: Text(
            kIsWeb
                ? 'Receipt downloaded successfully.'
                : 'Receipt saved successfully.',
          ),
        ),
      );
    } catch (error) {
      if (!mounted) {
        return;
      }

      ScaffoldMessenger.of(context).showSnackBar(
        SnackBar(
          content: Text(
            error.toString().replaceFirst(
                  'Exception: ',
                  '',
                ),
          ),
        ),
      );
    } finally {
      if (mounted) {
        setState(() {
          isProcessing = false;
        });
      }
    }
  }

  Widget detailRow(
    String label,
    String value,
  ) {
    return Padding(
      padding: const EdgeInsets.symmetric(
        vertical: 9,
      ),
      child: Row(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: <Widget>[
          SizedBox(
            width: 115,
            child: Text(
              label,
              style: const TextStyle(
                fontSize: 12,
                color: Color(
                  0xFF718078,
                ),
              ),
            ),
          ),
          Expanded(
            child: SelectableText(
              value,
              textAlign: TextAlign.right,
              style: const TextStyle(
                fontSize: 12.5,
                fontWeight: FontWeight.w700,
                color: Color(
                  0xFF26362E,
                ),
              ),
            ),
          ),
        ],
      ),
    );
  }

  Widget buildReceiptCard() {
    final narration = textValue(
      transaction['narration'],
      fallback: 'Business transaction',
    );

    final reference = textValue(
      transaction['reference'],
    );

    final type = textValue(
      transaction['type'],
    );

    final direction = textValue(
      transaction['direction'],
    );

    final counterparty = textValue(
      metadata['counterpartyBusinessWalletId'],
      fallback: '',
    );

    final bank = textValue(
      metadata['bankName'],
      fallback: '',
    );

    final accountNumber = textValue(
      metadata['accountNumber'],
      fallback: '',
    );

    final accountName = textValue(
      metadata['accountName'],
      fallback: '',
    );

    return Container(
      color: const Color(
        0xFFF7F9F8,
      ),
      padding: const EdgeInsets.all(
        18,
      ),
      child: Container(
        padding: const EdgeInsets.all(
          22,
        ),
        decoration: BoxDecoration(
          color: Colors.white,
          borderRadius: BorderRadius.circular(
            24,
          ),
          border: Border.all(
            color: const Color(
              0xFFE7ECE9,
            ),
          ),
        ),
        child: Column(
          mainAxisSize: MainAxisSize.min,
          children: <Widget>[
            Row(
              mainAxisAlignment: MainAxisAlignment.center,
              children: const <Widget>[
                Icon(
                  Icons.account_balance_wallet_rounded,
                  color: primaryGreen,
                  size: 25,
                ),
                SizedBox(width: 8),
                Text(
                  'ServicePay',
                  style: TextStyle(
                    fontSize: 22,
                    fontWeight: FontWeight.w900,
                    color: Color(
                      0xFF17231D,
                    ),
                  ),
                ),
              ],
            ),
            const SizedBox(height: 20),
            Container(
              width: 58,
              height: 58,
              decoration: const BoxDecoration(
                color: Color(
                  0xFFEAF7F0,
                ),
                shape: BoxShape.circle,
              ),
              child: Icon(
                isCredit ? Icons.south_west_rounded : Icons.north_east_rounded,
                color: primaryGreen,
                size: 29,
              ),
            ),
            const SizedBox(
              height: 14,
            ),
            Text(
              isCredit ? 'Money Received' : 'Money Sent',
              style: const TextStyle(
                fontSize: 14,
                fontWeight: FontWeight.w700,
                color: Color(
                  0xFF66756E,
                ),
              ),
            ),
            const SizedBox(
              height: 6,
            ),
            Text(
              money(
                transaction['amount'],
              ),
              style: const TextStyle(
                fontSize: 36,
                fontWeight: FontWeight.w900,
                color: Color(
                  0xFF17231D,
                ),
              ),
            ),
            const SizedBox(
              height: 11,
            ),
            Container(
              padding: const EdgeInsets.symmetric(
                horizontal: 12,
                vertical: 7,
              ),
              decoration: BoxDecoration(
                color: const Color(
                  0xFFEAF7F0,
                ),
                borderRadius: BorderRadius.circular(
                  100,
                ),
              ),
              child: Text(
                status,
                style: const TextStyle(
                  color: primaryGreen,
                  fontSize: 11,
                  fontWeight: FontWeight.w900,
                ),
              ),
            ),
            const SizedBox(
              height: 20,
            ),
            const Divider(),
            detailRow(
              'Business',
              businessName.isEmpty ? 'ServicePay Business' : businessName,
            ),
            detailRow(
              'Business ID',
              businessWalletId.isEmpty ? '-' : businessWalletId,
            ),
            detailRow(
              'Description',
              narration,
            ),
            detailRow(
              'Type',
              type,
            ),
            detailRow(
              'Direction',
              direction,
            ),
            detailRow(
              'Reference',
              reference,
            ),
            detailRow(
              'Date & Time',
              formatDateTime(
                transaction['createdAt'],
              ),
            ),
            if (counterparty.isNotEmpty)
              detailRow(
                'Counterparty ID',
                counterparty,
              ),
            if (bank.isNotEmpty)
              detailRow(
                'Bank',
                bank,
              ),
            if (accountNumber.isNotEmpty)
              detailRow(
                'Account Number',
                accountNumber,
              ),
            if (accountName.isNotEmpty)
              detailRow(
                'Account Name',
                accountName,
              ),
            if (transaction['balanceBefore'] != null)
              detailRow(
                'Balance Before',
                money(
                  transaction['balanceBefore'],
                ),
              ),
            if (transaction['balanceAfter'] != null)
              detailRow(
                'Balance After',
                money(
                  transaction['balanceAfter'],
                ),
              ),
            const SizedBox(
              height: 8,
            ),
            const Divider(),
            const SizedBox(
              height: 10,
            ),
            const Row(
              mainAxisAlignment: MainAxisAlignment.center,
              children: <Widget>[
                Icon(
                  Icons.verified_user_rounded,
                  color: primaryGreen,
                  size: 18,
                ),
                SizedBox(
                  width: 7,
                ),
                Flexible(
                  child: Text(
                    'Secured by ServicePay',
                    style: TextStyle(
                      color: Color(
                        0xFF607068,
                      ),
                      fontWeight: FontWeight.w700,
                    ),
                  ),
                ),
              ],
            ),
            const SizedBox(
              height: 8,
            ),
            const Text(
              'One Platform, Many Solutions.',
              style: TextStyle(
                fontSize: 10.5,
                color: Color(
                  0xFF7A8780,
                ),
              ),
            ),
          ],
        ),
      ),
    );
  }

  @override
  Widget build(
    BuildContext context,
  ) {
    return Scaffold(
      backgroundColor: const Color(
        0xFFF7F9F8,
      ),
      appBar: AppBar(
        title: const Text(
          'Transaction Receipt',
          style: TextStyle(
            fontWeight: FontWeight.w800,
          ),
        ),
        backgroundColor: const Color(
          0xFFF7F9F8,
        ),
        surfaceTintColor: Colors.transparent,
      ),
      body: ListView(
        padding: const EdgeInsets.fromLTRB(
          0,
          8,
          0,
          30,
        ),
        children: <Widget>[
          Screenshot(
            controller: screenshotController,
            child: buildReceiptCard(),
          ),
          const SizedBox(
            height: 14,
          ),
          Padding(
            padding: const EdgeInsets.symmetric(
              horizontal: 18,
            ),
            child: Row(
              children: <Widget>[
                Expanded(
                  child: OutlinedButton.icon(
                    onPressed: isProcessing ? null : shareReceipt,
                    icon: const Icon(
                      Icons.share_rounded,
                    ),
                    label: const Text(
                      'Share',
                    ),
                  ),
                ),
                const SizedBox(
                  width: 10,
                ),
                Expanded(
                  child: FilledButton.icon(
                    style: FilledButton.styleFrom(
                      backgroundColor: primaryGreen,
                    ),
                    onPressed: isProcessing ? null : downloadReceipt,
                    icon: const Icon(
                      Icons.download_rounded,
                    ),
                    label: const Text(
                      'Download',
                    ),
                  ),
                ),
              ],
            ),
          ),
          const SizedBox(
            height: 10,
          ),
          Padding(
            padding: const EdgeInsets.symmetric(
              horizontal: 18,
            ),
            child: TextButton.icon(
              onPressed: copyReceipt,
              icon: const Icon(
                Icons.copy_rounded,
              ),
              label: const Text(
                'Copy Receipt Text',
              ),
            ),
          ),
        ],
      ),
    );
  }
}
