import 'package:flutter/material.dart';
import 'package:flutter/services.dart';

class BusinessWalletTransactionReceiptScreen extends StatelessWidget {
  final Map<String, dynamic> transaction;
  final String businessName;
  final String businessWalletId;

  const BusinessWalletTransactionReceiptScreen({
    super.key,
    required this.transaction,
    required this.businessName,
    required this.businessWalletId,
  });

  static const Color primaryGreen = Color(0xFF08783E);

  double _toDouble(dynamic value) {
    return double.tryParse(
          value?.toString() ?? '',
        ) ??
        0;
  }

  String _money(dynamic value) {
    return '₦${_toDouble(value).toStringAsFixed(2)}';
  }

  String _text(
    dynamic value, {
    String fallback = '-',
  }) {
    final result = value?.toString().trim() ?? '';

    return result.isEmpty ? fallback : result;
  }

  String _dateTime(dynamic value) {
    final raw = value?.toString().trim() ?? '';

    if (raw.isEmpty) {
      return '-';
    }

    try {
      final dt = DateTime.parse(raw).toLocal();

      final day = dt.day.toString().padLeft(2, '0');

      final month = dt.month.toString().padLeft(2, '0');

      final year = dt.year.toString();

      final hour = dt.hour.toString().padLeft(2, '0');

      final minute = dt.minute.toString().padLeft(2, '0');

      return '$day/$month/$year  $hour:$minute';
    } catch (_) {
      return raw;
    }
  }

  Map<String, dynamic> get _metadata {
    final value = transaction['metadata'];

    if (value is Map) {
      return Map<String, dynamic>.from(
        value,
      );
    }

    return <String, dynamic>{};
  }

  bool get _isCredit {
    final direction = _text(
      transaction['direction'],
      fallback: '',
    ).toUpperCase();

    return direction == 'CREDIT';
  }

  String get _status {
    return _text(
      transaction['status'],
      fallback: 'SUCCESSFUL',
    ).toUpperCase();
  }

  String get _receiptText {
    final buffer = StringBuffer();

    buffer.writeln('SERVICEPAY BUSINESS WALLET RECEIPT');
    buffer.writeln('');
    buffer.writeln(
      'Business: ${businessName.isEmpty ? 'ServicePay Business' : businessName}',
    );
    buffer.writeln(
      'Business ID: ${businessWalletId.isEmpty ? '-' : businessWalletId}',
    );
    buffer.writeln(
      'Transaction: ${_text(transaction['narration'], fallback: 'Business transaction')}',
    );
    buffer.writeln(
      'Amount: ${_money(transaction['amount'])}',
    );
    buffer.writeln(
      'Type: ${_text(transaction['type'])}',
    );
    buffer.writeln(
      'Direction: ${_text(transaction['direction'])}',
    );
    buffer.writeln(
      'Status: $_status',
    );
    buffer.writeln(
      'Reference: ${_text(transaction['reference'])}',
    );
    buffer.writeln(
      'Date: ${_dateTime(transaction['createdAt'])}',
    );

    final counterparty = _text(
      _metadata['counterpartyBusinessWalletId'],
      fallback: '',
    );

    if (counterparty.isNotEmpty) {
      buffer.writeln(
        'Counterparty Business ID: $counterparty',
      );
    }

    final bankName = _text(
      _metadata['bankName'],
      fallback: '',
    );

    if (bankName.isNotEmpty) {
      buffer.writeln(
        'Bank: $bankName',
      );
    }

    final accountNumber = _text(
      _metadata['accountNumber'],
      fallback: '',
    );

    if (accountNumber.isNotEmpty) {
      buffer.writeln(
        'Account Number: $accountNumber',
      );
    }

    buffer.writeln('');
    buffer.writeln(
      'Generated by ServicePay',
    );

    return buffer.toString();
  }

  Future<void> _copyReceipt(
    BuildContext context,
  ) async {
    await Clipboard.setData(
      ClipboardData(
        text: _receiptText,
      ),
    );

    if (!context.mounted) {
      return;
    }

    ScaffoldMessenger.of(context).showSnackBar(
      const SnackBar(
        content: Text(
          'Receipt copied successfully.',
        ),
      ),
    );
  }

  Widget _detailRow(
    String label,
    String value,
  ) {
    return Padding(
      padding: const EdgeInsets.symmetric(
        vertical: 9,
      ),
      child: Row(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: <Widget>[
          SizedBox(
            width: 115,
            child: Text(
              label,
              style: const TextStyle(
                fontSize: 12,
                color: Color(0xFF718078),
              ),
            ),
          ),
          Expanded(
            child: SelectableText(
              value,
              textAlign: TextAlign.right,
              style: const TextStyle(
                fontSize: 12.5,
                fontWeight: FontWeight.w700,
                color: Color(0xFF26362E),
              ),
            ),
          ),
        ],
      ),
    );
  }

  @override
  Widget build(
    BuildContext context,
  ) {
    final narration = _text(
      transaction['narration'],
      fallback: 'Business transaction',
    );

    final reference = _text(
      transaction['reference'],
    );

    final type = _text(
      transaction['type'],
    );

    final direction = _text(
      transaction['direction'],
    );

    final balanceBefore = transaction['balanceBefore'];

    final balanceAfter = transaction['balanceAfter'];

    final counterparty = _text(
      _metadata['counterpartyBusinessWalletId'],
      fallback: '',
    );

    final bankName = _text(
      _metadata['bankName'],
      fallback: '',
    );

    final accountNumber = _text(
      _metadata['accountNumber'],
      fallback: '',
    );

    final accountName = _text(
      _metadata['accountName'],
      fallback: '',
    );

    return Scaffold(
      backgroundColor: const Color(0xFFF7F9F8),
      appBar: AppBar(
        title: const Text(
          'Transaction Receipt',
          style: TextStyle(
            fontWeight: FontWeight.w800,
          ),
        ),
        backgroundColor: const Color(0xFFF7F9F8),
        surfaceTintColor: Colors.transparent,
      ),
      body: ListView(
        padding: const EdgeInsets.fromLTRB(
          18,
          8,
          18,
          30,
        ),
        children: <Widget>[
          Container(
            padding: const EdgeInsets.all(
              22,
            ),
            decoration: BoxDecoration(
              color: Colors.white,
              borderRadius: BorderRadius.circular(
                24,
              ),
              border: Border.all(
                color: const Color(
                  0xFFE7ECE9,
                ),
              ),
            ),
            child: Column(
              children: <Widget>[
                Container(
                  width: 58,
                  height: 58,
                  decoration: BoxDecoration(
                    color: const Color(
                      0xFFEAF7F0,
                    ),
                    shape: BoxShape.circle,
                  ),
                  child: Icon(
                    _isCredit
                        ? Icons.south_west_rounded
                        : Icons.north_east_rounded,
                    color: primaryGreen,
                    size: 29,
                  ),
                ),
                const SizedBox(
                  height: 14,
                ),
                Text(
                  _isCredit ? 'Money Received' : 'Money Sent',
                  style: const TextStyle(
                    fontSize: 14,
                    fontWeight: FontWeight.w700,
                    color: Color(
                      0xFF66756E,
                    ),
                  ),
                ),
                const SizedBox(
                  height: 6,
                ),
                Text(
                  _money(
                    transaction['amount'],
                  ),
                  style: const TextStyle(
                    fontSize: 36,
                    fontWeight: FontWeight.w900,
                    color: Color(
                      0xFF17231D,
                    ),
                  ),
                ),
                const SizedBox(
                  height: 11,
                ),
                Container(
                  padding: const EdgeInsets.symmetric(
                    horizontal: 12,
                    vertical: 7,
                  ),
                  decoration: BoxDecoration(
                    color: const Color(
                      0xFFEAF7F0,
                    ),
                    borderRadius: BorderRadius.circular(
                      100,
                    ),
                  ),
                  child: Text(
                    _status,
                    style: const TextStyle(
                      color: primaryGreen,
                      fontSize: 11,
                      fontWeight: FontWeight.w900,
                    ),
                  ),
                ),
                const SizedBox(
                  height: 20,
                ),
                const Divider(),
                _detailRow(
                  'Business',
                  businessName.isEmpty ? 'ServicePay Business' : businessName,
                ),
                _detailRow(
                  'Business ID',
                  businessWalletId.isEmpty ? '-' : businessWalletId,
                ),
                _detailRow(
                  'Description',
                  narration,
                ),
                _detailRow(
                  'Type',
                  type,
                ),
                _detailRow(
                  'Direction',
                  direction,
                ),
                _detailRow(
                  'Reference',
                  reference,
                ),
                _detailRow(
                  'Date & Time',
                  _dateTime(
                    transaction['createdAt'],
                  ),
                ),
                if (counterparty.isNotEmpty)
                  _detailRow(
                    'Counterparty ID',
                    counterparty,
                  ),
                if (bankName.isNotEmpty)
                  _detailRow(
                    'Bank',
                    bankName,
                  ),
                if (accountNumber.isNotEmpty)
                  _detailRow(
                    'Account Number',
                    accountNumber,
                  ),
                if (accountName.isNotEmpty)
                  _detailRow(
                    'Account Name',
                    accountName,
                  ),
                if (balanceBefore != null)
                  _detailRow(
                    'Balance Before',
                    _money(
                      balanceBefore,
                    ),
                  ),
                if (balanceAfter != null)
                  _detailRow(
                    'Balance After',
                    _money(
                      balanceAfter,
                    ),
                  ),
                const SizedBox(
                  height: 8,
                ),
                const Divider(),
                const SizedBox(
                  height: 10,
                ),
                Row(
                  mainAxisAlignment: MainAxisAlignment.center,
                  children: <Widget>[
                    const Icon(
                      Icons.verified_user_rounded,
                      color: primaryGreen,
                      size: 18,
                    ),
                    const SizedBox(
                      width: 7,
                    ),
                    const Flexible(
                      child: Text(
                        'Secured by ServicePay',
                        style: TextStyle(
                          color: Color(
                            0xFF607068,
                          ),
                          fontWeight: FontWeight.w700,
                        ),
                      ),
                    ),
                  ],
                ),
              ],
            ),
          ),
          const SizedBox(height: 14),
          SizedBox(
            width: double.infinity,
            height: 52,
            child: FilledButton.icon(
              style: FilledButton.styleFrom(
                backgroundColor: primaryGreen,
              ),
              onPressed: () => _copyReceipt(
                context,
              ),
              icon: const Icon(
                Icons.copy_rounded,
              ),
              label: const Text(
                'Copy Receipt',
                style: TextStyle(
                  fontWeight: FontWeight.w800,
                ),
              ),
            ),
          ),
          const SizedBox(height: 14),
          const Center(
            child: Text(
              'ServicePay • One Platform, Many Solutions.',
              textAlign: TextAlign.center,
              style: TextStyle(
                fontSize: 11,
                color: Color(
                  0xFF7A8780,
                ),
              ),
            ),
          ),
        ],
      ),
    );
  }
}
