const mongoose = require("mongoose");
const schema = new mongoose.Schema({
  sourceType: { type: String, required: true, trim: true, uppercase: true, index: true },
  version: { type: Number, required: true, min: 1 },
  calculation: { type: String, enum: ["PERCENT", "FIXED"], required: true },
  value: { type: Number, required: true, min: 0 },
  minimumTransactionAmount: { type: Number, default: 0, min: 0 },
  maximumCommission: { type: Number, default: null, min: 0 },
  // Hard aggregate ceiling for all payouts generated by this rule. Legacy
  // rules without an explicit bound are intentionally ineligible for payout.
  availableMargin: { type: Number, default: null, min: 0 },
  allocatedMargin: { type: Number, default: 0, min: 0 },
  partnerRate: { type: Number, default: null, min: 0 },
  officerRate: { type: Number, default: null, min: 0 },
  partnerOverrideRate: { type: Number, default: null, min: 0 },
  status: { type: String, enum: ["ACTIVE", "DISABLED"], default: "ACTIVE", index: true },
  effectiveFrom: { type: Date, default: Date.now },
  createdBy: { type: mongoose.Schema.Types.ObjectId, ref: "User", required: true },
}, { timestamps: true });
schema.index({ sourceType: 1, version: 1 }, { unique: true });
module.exports = mongoose.model("BusinessPartnerCommissionRule", schema);