name: Build ServicePay Admin APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Set up latest stable Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: false

      - name: Show Flutter version
        run: flutter --version

      - name: Clean project
        run: flutter clean

      - name: Install dependencies
        run: flutter pub get

      - name: Build Admin APK
        run: flutter build apk --release

      - name: Upload Admin APK
        uses: actions/upload-artifact@v4
        with:
          name: ServicePay-Admin-APK
          path: build/app/outputs/flutter-apk/app-release.apk
          if-no-files-found: error